services:
  db:
    image: postgres:18.1
    container_name: erp-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-erp}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres18_data:/var/lib/postgresql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  postgres18_data: